/**
 * In-app Help topics. YAML keys here must stay in sync with
 * `src/core/YamlFrontMatter.ts` (TOP_KEYS / LAYOUT_KEYS / STYLE_KEYS / PREF_KEYS
 * / HEADING_STYLE_KEYS). Add further topics as extra Help menu items.
 */

export type HelpTopic = {
  id: string;
  title: string;
  body: string;
};

export const HELP_YAML: HelpTopic = {
  id: "yaml",
  title: "YAML front matter — all parameters",
  body: [
    "Optional header: the first non-blank line must be --- and a later line must",
    "be --- to close. Keys are lowercase (raga: not Raagam:). # starts a comment.",
    "Unknown keys are rejected. YAML is translated into classic CMNT directives",
    "(Heading:, Raagam:, Tala:, …) before parse; classic files without --- are",
    "unchanged.",
    "",
    "---",
    "title: Song title",
    "composer: Composer name",
    "language: Tamil",
    "raga: Sri                 # aliases: ragam, raagam",
    "ragaDisplay: pUrNa@ncandrikA   # aliases: ragamDisplay, raagamDisplay",
    "melakarta: 22             # 1–72; must match raga if both are set",
    "tala: Adi                 # REQUIRED to pick the cycle; alias: talam",
    "talaDisplay: Adi          # optional roman spelling only; aliases: talamDisplay",
    "speed: 0                  # alias: defaultSpeed — notation density 0 / 1 / 2",
    "speedMarks: true          # accepted; not used in the current SVG render",
    "phraseEnds: show          # show | hide | handle | handlethick",
    "cyclesPerRow: 2           # 1–8; also allowed under layout:",
    "rowSpacing: 1.0           # 0.3–3.0; also under layout:",
    "cellSpacing: 1.0          # 0.1–3.0; also under layout:",
    "orientation: landscape    # portrait | landscape; File → Export PDF",
    "layout:",
    "  type: krithi",
    "  width: full",
    "  orientation: portrait",
    "  cyclesPerRow: 2",
    "  rowSpacing: 1.0",
    "  cellSpacing: 1.0",
    "style:",
    "  swara: { color: blue, size: 13, font: Georgia }",
    "  lyric:",
    "    color: black",
    "    size: 11                 # shrinks dense Tamil sahityam",
    "    font: Noto Sans Tamil    # quote names with spaces in { flow } maps",
    "  heading: { color: black, size: 16, bold: true }",
    "  gamaka: { color: gray, size: 11 }",
    "---",
    "",
    "Then the song body (classic lines):",
    "Pallavi:",
    "S: s r g m | p d n s'",
    "L: sa ri ga ma pa da ni sa",
    "",
    "========== TOP-LEVEL KEYS ==========",
    "",
    "title            Score title heading. Plain string, or a block (see Title /",
    "                 composer block). Default style: bold, center, size 20.",
    "composer         Composer heading. Plain string or block. Default: italic,",
    "                 center, size 16, tight spacing.",
    "language         Score script: English | Tamil | Telugu | Kannada | Sanskrit.",
    "                 Applied to title/composer and to the ragam/talam heading.",
    "raga             Catalogue raga name (roman). Aliases: ragam, raagam.",
    "ragaDisplay      Optional CMNT-roman spelling for the printed ragam line",
    "                 (with @ / # / ~n / %n; Tamil varga subscripts). Aliases: ragamDisplay, raagamDisplay.",
    "                 Does not change which raga is looked up — raga: does that.",
    "melakarta        Integer 1–72. Must agree with raga: if both are present.",
    "tala             Tala cycle (Adi, Rupaka, misracApu, …). Alias: talam.",
    "                 This key selects the tala. Required for S: lines.",
    "talaDisplay      Optional roman spelling override only. Aliases: talamDisplay.",
    "                 If tala: is missing and talaDisplay: is itself a known tala",
    "                 name, it is promoted to tala:. Otherwise an error is raised.",
    "speed            Notation DefaultSpeed 0 / 1 / 2 (notes per akshara after",
    "                 layout shift). Alias: defaultSpeed. Chapu often uses 0.",
    "                 This is not Play-menu BPM.",
    "speedMarks       Passed through as SpeedMarks:. Not drawn in the current SVG.",
    "phraseEnds       Phrase-end hyphen drawing: show | hide | handle | handlethick.",
    "cyclesPerRow     How many tala cycles in one score row (1–8). May also sit",
    "                 under layout:. Top-level wins if both are set.",
    "rowSpacing       Vertical row scale 0.3–3.0. Also under layout:.",
    "cellSpacing      Horizontal cell scale 0.1–3.0. Also under layout:.",
    "orientation     portrait | landscape. File → Export PDF uses US Letter in",
    "                 this orientation (landscape is wider — dense sahityam rows",
    "                 have more room). Also allowed under layout:. Top-level",
    "                 wins if both are set. Classic: Orientation: Landscape",
    "layout           Nested map (preferred) or a single string (emits Layout:).",
    "style            Nested map of swara / lyric / heading / gamaka prefs.",
    "",
    "========== TITLE / COMPOSER BLOCK ==========",
    "",
    "Instead of a plain string:",
    "title:",
    "  text: Endaro Mahanubhavulu    # required in a block",
    "  bold: true                    # true / false",
    "  italic: false",
    "  align: center                 # passed through to Heading:",
    "  size: 20",
    "  font: Georgia",
    "  color: blue",
    "",
    "Same keys under composer:. Unknown keys under the block are rejected.",
    "",
    "========== layout: ==========",
    "",
    "type          krithi (also kriti) | gitam (also geetam) | varnam",
    "              Gitam keeps DefaultSpeed 0/1/2 as 1/2/4 notes per akshara.",
    "              Krithi/varnam (and omitted type) apply the krithi speed shift.",
    "width         full → FullWidth   compact → Compact",
    "orientation   portrait | landscape   (emits Orientation:; top-level wins)",
    "cyclesPerRow  1–8   (if not already set at top level)",
    "rowSpacing    0.3–3.0",
    "cellSpacing   0.1–3.0",
    "",
    "If type or width is set, a Layout: line is emitted (type defaults to Krithi",
    "when only width is given).",
    "",
    "========== style: ==========",
    "",
    "Nested maps (flow { … } or indented). Each of:",
    "  swara     → SwaraPrefs:",
    "  lyric     → LyricPrefs:",
    "  heading   → HeadingPrefs:",
    "  gamaka    → GamakaPrefs:",
    "",
    "Pref keys (any subset):",
    "  color     named or CSS-style color token",
    "  size      integer point size (drawn as px on the SVG). For lyric this",
    "            also drives how wide each sahityam syllable is measured, so",
    "            a slightly smaller size (10–12) uncrowds Tamil rows with",
    "            varga subscripts (க₁, தோ₁ம்) without wrapping mid-anga.",
    "  font      one family name (Noto Sans Tamil, Georgia, …). Overrides the",
    "            school / language font for that role. Quote names with spaces",
    "            inside a flow map: { font: \"Noto Sans Tamil\", size: 11 }",
    "            Indented form may omit quotes: font: Noto Sans Tamil",
    "  bold      true adds bold",
    "",
    "Example — readable sahityam on a packed anupallavi, landscape PDF:",
    "  orientation: landscape",
    "  style:",
    "    lyric:",
    "      font: Noto Sans Tamil",
    "      size: 11",
    "",
    "Classic equivalents (no --- header): LyricPrefs: 11,Noto Sans Tamil",
    "and Orientation: Landscape. Size and font apply to both the printed",
    "glyphs and the cell-width layout; color-only prefs leave the school font.",
    "",
    "========== AFTER THE CLOSING --- ==========",
    "",
    "Classic body (not YAML keys): Heading:, Language:, Raagam:, Tala:,",
    "S: / L: pairs, Pallavi: / Anupallavi: / Charanam: labels, Insert → Gamaka",
    "and speed marks. Bars | || on L: are ignored for lyric count.",
    "An S: line with no following L: (ciTTaswaram, muktAyi) prints without a",
    "blank lyric band; padavarnam rows that do have L: text keep the gap.",
  ].join("\n"),
};

export const HELP_COMPOSER: HelpTopic = {
  id: "composer",
  title: "Composer — using CMNT Web",
  body: [
    "CMNT Web is a Path A composer: TypeScript core, SVG score, CSS school",
    "theming. Songs are plain text (.txt). This topic is the place to add further",
    "tool notes as the product grows.",
    "",
    "MENUS",
    "  File     New / Open / Save / Save As, Update Preview, samples, export SVG/PNG/PDF",
    "  View     Live update, score language, school, ragam display, Edit Aro/Ava",
    "  Play     Local vite, or public site with ?audio=1. BPM, click, Pitch (Sa),",
    "           instrument, practice speed, Play, Stop. Hidden on the public Pages build.",
    "  Insert   Gamaka marks, 2nd/3rd/4th speed, Language: line, Raagam/Tala,",
    "           headings, S: / L: templates",
    "  Help     YAML parameter reference and this overview",
    "",
    "PANES",
    "  Score (WYSIWYG) on top; S:/L: source below. Drag the horizontal bar to",
    "  resize. The source pane is larger by default because a pair is finished",
    "  in the score once typed.",
    "",
    "TYPING",
    "  Live update (View) re-parses while you type S:/L: pairs.",
    "  File → Update Preview (⌘/Ctrl+Enter) if live update is off.",
    "  A { sA r s r … }(kh) cluster fills one parent beat; sA is twice a short note.",
    "  Phrase-end hyphen (r-) is a breath in playback without shifting tala.",
    "",
    "TAMIL n (ந / ன)",
    "  Auto: ந் before த/த (kan+dan → க₁ந் த₃ன்), ன் at a word end or before ற/ய",
    "  (kun+Ran → கு₁ன்றன்). Split L: tokens look like one word if nothing is blank",
    "  between them, so கந்தன் தரி… as kan dan thari can print த₃ந்.",
    "  Override on the syllable:  ka@n / @n → ந்    da%n / %n → ன்",
    "  Mark the next word with @ so the previous n does not look across (@thari).",
    "  #n → ங்    ~n → ஞ்    N → ண    R → ற",
    "  Insert → Tamil n (ந / ன) writes the marker at the caret or on a selected n.",
    "",
    "TAMIL VARGA (க ச ட த ப)",
    "  Tamil has one letter per varga. Lyrics mark the roman sound with a",
    "  subscript after the akshara:  1 unvoiced  2 aspirated  3 voiced  4 voiced-asp.",
    "  ka/kha/ga/gha → க₁ க₂ க₃ க₄    ca/cha/ja/jha → ச₁ ச₂ ஜ₃ ஜ₄",
    "  Ta/Tha/Da/Dha → ட₁ ட₂ ட₃ ட₄    ta/tha/da/dha → த₁ த₂ த₃ த₄",
    "  pa/pha/ba/bha → ப₁ ப₂ ப₃ ப₄",
    "  ksh → க்ஷ (Grantha conjunct, not க் ஷ).  #n → ங்    ~n → ஞ்    ja → ஜ₃",
    "  Swara letters on the score stay unmarked (க for ga, not க₃).",
    "",
    "RAGAM / TALAM",
    "  Catalogue names stay roman on Indic scores unless you set ragaDisplay /",
    "  View → Raagam display. Talam uses the catalogue; TalamDisplay is spelling",
    "  only. Edit Aro/Ava saves janya corrections in this browser (not melakartas).",
    "",
    "YAML PAGE AND FONTS",
    "  orientation: landscape | portrait — File → Export PDF uses that Letter",
    "  page. Landscape is wider; use it when anupallavi sahityam crowds.",
    "  style.lyric.font / style.lyric.size — printed sahityam font and size;",
    "  cell widths follow the measured syllables. Same keys under style.swara.",
    "  Help → YAML front matter has copy-paste examples.",
    "",
    "SWARA-ONLY ROWS",
    "  ciTTaswaram / muktAyi swaram lines that have S: but no real L: syllables",
    "  no longer reserve a blank sahityam band (that used to stretch the row).",
    "  Padavarnam (or any S: that has an L: with text) still keeps lyric space.",
    "",
    "FILES",
    "  The editor source IS the .txt. File → Save (.txt) / Save As writes it",
    "  (File System Access when the browser allows, otherwise a download).",
    "  SVG/PDF export is a picture of the score, not a substitute for the .txt.",
    "  Switching songs (sample / New / Open) keeps the outgoing source in this",
    "  browser — File → Restore previous song. A refresh restores the last",
    "  unsaved draft from this same browser. Songs are not hosted on the site.",
    "",
    "AUDIO (experimental)",
    "  Practice sketch, not a finished gamaka model. Unlocked in npm run dev and",
    "  with ?audio=1 on Pages. Public visitors do not see Play. Pitch (Sa) sets the",
    "  tonic (default C4); the rest of the sketch shifts with it.",
  ].join("\n"),
};

export const HELP_TOPICS: readonly HelpTopic[] = [HELP_YAML, HELP_COMPOSER];
